services:
    sacrpkg_crud.action_factory:
        class: sacrpkg\CrudBundle\Action\ActionFactory
        public: true
        arguments:
            - '@doctrine'
            - '@request_stack'
            - '@form.factory'
            - '@router.default'
            - '@parameter_bag'

    sacrpkg\CrudBundle\Action\ActionFactoryInterface: '@sacrpkg_crud.action_factory'

    sacrpkg_crud.paginator:
        class: sacrpkg\CrudBundle\Model\Paginator
        public: true
        arguments:
            - '@request_stack'


    sacrpkg\CrudBundle\Model\Paginator: '@sacrpkg_crud.paginator'

    sacrpkg_crud.filter:
        class: sacrpkg\CrudBundle\Model\Filter
        public: true
        arguments:
            - '@request_stack'


    sacrpkg\CrudBundle\Model\Filter: '@sacrpkg_crud.filter'

    sacrpkg_crud.doctrine_reader:
        class: sacrpkg\CrudBundle\Model\Reader\DoctrineReader
        public: true
        arguments:
            - '@doctrine'


    sacrpkg\CrudBundle\Model\Reader\DoctrineReader: '@sacrpkg_crud.doctrine_reader'